/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FrRouteImport } from './routes/fr'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ArRouteImport } from './routes/ar'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as TeropdfRouteImport } from './routes/Teropdf'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as ArIndexRouteImport } from './routes/ar/index'
import { Route as FrTermsRouteImport } from './routes/fr/terms'
import { Route as FrPrivacyPolicyRouteImport } from './routes/fr/privacy-policy'
import { Route as FrNewsRouteImport } from './routes/fr/news'
import { Route as FrLearnRouteImport } from './routes/fr/learn'
import { Route as FrFeaturesRouteImport } from './routes/fr/features'
import { Route as FrDownloadRouteImport } from './routes/fr/download'
import { Route as FrDeleteAccountRouteImport } from './routes/fr/delete-account'
import { Route as FrContactRouteImport } from './routes/fr/contact'
import { Route as FrCompareRouteImport } from './routes/fr/compare'
import { Route as FrAiToolsRouteImport } from './routes/fr/ai-tools'
import { Route as ArTermsRouteImport } from './routes/ar/terms'
import { Route as ArPrivacyPolicyRouteImport } from './routes/ar/privacy-policy'
import { Route as ArNewsRouteImport } from './routes/ar/news'
import { Route as ArLearnRouteImport } from './routes/ar/learn'
import { Route as ArFeaturesRouteImport } from './routes/ar/features'
import { Route as ArDownloadRouteImport } from './routes/ar/download'
import { Route as ArDeleteAccountRouteImport } from './routes/ar/delete-account'
import { Route as ArContactRouteImport } from './routes/ar/contact'
import { Route as ArCompareRouteImport } from './routes/ar/compare'
import { Route as ArAiToolsRouteImport } from './routes/ar/ai-tools'
import { Route as TeropdfTermsRouteImport } from './routes/Teropdf/terms'
import { Route as TeropdfPrivacyPolicyRouteImport } from './routes/Teropdf/privacy-policy'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TeropdfRoute = TeropdfRouteImport.update({
  id: '/Teropdf',
  path: '/Teropdf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrRoute,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArRoute,
} as any)
const FrTermsRoute = FrTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => FrRoute,
} as any)
const FrPrivacyPolicyRoute = FrPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => FrRoute,
} as any)
const FrNewsRoute = FrNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => FrRoute,
} as any)
const FrLearnRoute = FrLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => FrRoute,
} as any)
const FrFeaturesRoute = FrFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => FrRoute,
} as any)
const FrDownloadRoute = FrDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => FrRoute,
} as any)
const FrDeleteAccountRoute = FrDeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => FrRoute,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => FrRoute,
} as any)
const FrCompareRoute = FrCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => FrRoute,
} as any)
const FrAiToolsRoute = FrAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => FrRoute,
} as any)
const ArTermsRoute = ArTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ArRoute,
} as any)
const ArPrivacyPolicyRoute = ArPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => ArRoute,
} as any)
const ArNewsRoute = ArNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ArRoute,
} as any)
const ArLearnRoute = ArLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => ArRoute,
} as any)
const ArFeaturesRoute = ArFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => ArRoute,
} as any)
const ArDownloadRoute = ArDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ArRoute,
} as any)
const ArDeleteAccountRoute = ArDeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => ArRoute,
} as any)
const ArContactRoute = ArContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ArRoute,
} as any)
const ArCompareRoute = ArCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => ArRoute,
} as any)
const ArAiToolsRoute = ArAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => ArRoute,
} as any)
const TeropdfTermsRoute = TeropdfTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => TeropdfRoute,
} as any)
const TeropdfPrivacyPolicyRoute = TeropdfPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => TeropdfRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Teropdf': typeof TeropdfRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/ar': typeof ArRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/fr': typeof FrRouteWithChildren
  '/learn': typeof LearnRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/Teropdf/privacy-policy': typeof TeropdfPrivacyPolicyRoute
  '/Teropdf/terms': typeof TeropdfTermsRoute
  '/ar/ai-tools': typeof ArAiToolsRoute
  '/ar/compare': typeof ArCompareRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/delete-account': typeof ArDeleteAccountRoute
  '/ar/download': typeof ArDownloadRoute
  '/ar/features': typeof ArFeaturesRoute
  '/ar/learn': typeof ArLearnRoute
  '/ar/news': typeof ArNewsRoute
  '/ar/privacy-policy': typeof ArPrivacyPolicyRoute
  '/ar/terms': typeof ArTermsRoute
  '/fr/ai-tools': typeof FrAiToolsRoute
  '/fr/compare': typeof FrCompareRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/delete-account': typeof FrDeleteAccountRoute
  '/fr/download': typeof FrDownloadRoute
  '/fr/features': typeof FrFeaturesRoute
  '/fr/learn': typeof FrLearnRoute
  '/fr/news': typeof FrNewsRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/fr/terms': typeof FrTermsRoute
  '/ar/': typeof ArIndexRoute
  '/fr/': typeof FrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Teropdf': typeof TeropdfRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/learn': typeof LearnRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/Teropdf/privacy-policy': typeof TeropdfPrivacyPolicyRoute
  '/Teropdf/terms': typeof TeropdfTermsRoute
  '/ar/ai-tools': typeof ArAiToolsRoute
  '/ar/compare': typeof ArCompareRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/delete-account': typeof ArDeleteAccountRoute
  '/ar/download': typeof ArDownloadRoute
  '/ar/features': typeof ArFeaturesRoute
  '/ar/learn': typeof ArLearnRoute
  '/ar/news': typeof ArNewsRoute
  '/ar/privacy-policy': typeof ArPrivacyPolicyRoute
  '/ar/terms': typeof ArTermsRoute
  '/fr/ai-tools': typeof FrAiToolsRoute
  '/fr/compare': typeof FrCompareRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/delete-account': typeof FrDeleteAccountRoute
  '/fr/download': typeof FrDownloadRoute
  '/fr/features': typeof FrFeaturesRoute
  '/fr/learn': typeof FrLearnRoute
  '/fr/news': typeof FrNewsRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/fr/terms': typeof FrTermsRoute
  '/ar': typeof ArIndexRoute
  '/fr': typeof FrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Teropdf': typeof TeropdfRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/ar': typeof ArRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/delete-account': typeof DeleteAccountRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/fr': typeof FrRouteWithChildren
  '/learn': typeof LearnRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/Teropdf/privacy-policy': typeof TeropdfPrivacyPolicyRoute
  '/Teropdf/terms': typeof TeropdfTermsRoute
  '/ar/ai-tools': typeof ArAiToolsRoute
  '/ar/compare': typeof ArCompareRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/delete-account': typeof ArDeleteAccountRoute
  '/ar/download': typeof ArDownloadRoute
  '/ar/features': typeof ArFeaturesRoute
  '/ar/learn': typeof ArLearnRoute
  '/ar/news': typeof ArNewsRoute
  '/ar/privacy-policy': typeof ArPrivacyPolicyRoute
  '/ar/terms': typeof ArTermsRoute
  '/fr/ai-tools': typeof FrAiToolsRoute
  '/fr/compare': typeof FrCompareRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/delete-account': typeof FrDeleteAccountRoute
  '/fr/download': typeof FrDownloadRoute
  '/fr/features': typeof FrFeaturesRoute
  '/fr/learn': typeof FrLearnRoute
  '/fr/news': typeof FrNewsRoute
  '/fr/privacy-policy': typeof FrPrivacyPolicyRoute
  '/fr/terms': typeof FrTermsRoute
  '/ar/': typeof ArIndexRoute
  '/fr/': typeof FrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Teropdf'
    | '/ai-tools'
    | '/ar'
    | '/compare'
    | '/contact'
    | '/delete-account'
    | '/download'
    | '/features'
    | '/fr'
    | '/learn'
    | '/news'
    | '/privacy-policy'
    | '/terms'
    | '/Teropdf/privacy-policy'
    | '/Teropdf/terms'
    | '/ar/ai-tools'
    | '/ar/compare'
    | '/ar/contact'
    | '/ar/delete-account'
    | '/ar/download'
    | '/ar/features'
    | '/ar/learn'
    | '/ar/news'
    | '/ar/privacy-policy'
    | '/ar/terms'
    | '/fr/ai-tools'
    | '/fr/compare'
    | '/fr/contact'
    | '/fr/delete-account'
    | '/fr/download'
    | '/fr/features'
    | '/fr/learn'
    | '/fr/news'
    | '/fr/privacy-policy'
    | '/fr/terms'
    | '/ar/'
    | '/fr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Teropdf'
    | '/ai-tools'
    | '/compare'
    | '/contact'
    | '/delete-account'
    | '/download'
    | '/features'
    | '/learn'
    | '/news'
    | '/privacy-policy'
    | '/terms'
    | '/Teropdf/privacy-policy'
    | '/Teropdf/terms'
    | '/ar/ai-tools'
    | '/ar/compare'
    | '/ar/contact'
    | '/ar/delete-account'
    | '/ar/download'
    | '/ar/features'
    | '/ar/learn'
    | '/ar/news'
    | '/ar/privacy-policy'
    | '/ar/terms'
    | '/fr/ai-tools'
    | '/fr/compare'
    | '/fr/contact'
    | '/fr/delete-account'
    | '/fr/download'
    | '/fr/features'
    | '/fr/learn'
    | '/fr/news'
    | '/fr/privacy-policy'
    | '/fr/terms'
    | '/ar'
    | '/fr'
  id:
    | '__root__'
    | '/'
    | '/Teropdf'
    | '/ai-tools'
    | '/ar'
    | '/compare'
    | '/contact'
    | '/delete-account'
    | '/download'
    | '/features'
    | '/fr'
    | '/learn'
    | '/news'
    | '/privacy-policy'
    | '/terms'
    | '/Teropdf/privacy-policy'
    | '/Teropdf/terms'
    | '/ar/ai-tools'
    | '/ar/compare'
    | '/ar/contact'
    | '/ar/delete-account'
    | '/ar/download'
    | '/ar/features'
    | '/ar/learn'
    | '/ar/news'
    | '/ar/privacy-policy'
    | '/ar/terms'
    | '/fr/ai-tools'
    | '/fr/compare'
    | '/fr/contact'
    | '/fr/delete-account'
    | '/fr/download'
    | '/fr/features'
    | '/fr/learn'
    | '/fr/news'
    | '/fr/privacy-policy'
    | '/fr/terms'
    | '/ar/'
    | '/fr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeropdfRoute: typeof TeropdfRouteWithChildren
  AiToolsRoute: typeof AiToolsRoute
  ArRoute: typeof ArRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  FrRoute: typeof FrRouteWithChildren
  LearnRoute: typeof LearnRoute
  NewsRoute: typeof NewsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Teropdf': {
      id: '/Teropdf'
      path: '/Teropdf'
      fullPath: '/Teropdf'
      preLoaderRoute: typeof TeropdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof FrRoute
    }
    '/ar/': {
      id: '/ar/'
      path: '/'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof ArRoute
    }
    '/fr/terms': {
      id: '/fr/terms'
      path: '/terms'
      fullPath: '/fr/terms'
      preLoaderRoute: typeof FrTermsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/privacy-policy': {
      id: '/fr/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/fr/privacy-policy'
      preLoaderRoute: typeof FrPrivacyPolicyRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/news': {
      id: '/fr/news'
      path: '/news'
      fullPath: '/fr/news'
      preLoaderRoute: typeof FrNewsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/learn': {
      id: '/fr/learn'
      path: '/learn'
      fullPath: '/fr/learn'
      preLoaderRoute: typeof FrLearnRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/features': {
      id: '/fr/features'
      path: '/features'
      fullPath: '/fr/features'
      preLoaderRoute: typeof FrFeaturesRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/download': {
      id: '/fr/download'
      path: '/download'
      fullPath: '/fr/download'
      preLoaderRoute: typeof FrDownloadRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/delete-account': {
      id: '/fr/delete-account'
      path: '/delete-account'
      fullPath: '/fr/delete-account'
      preLoaderRoute: typeof FrDeleteAccountRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/compare': {
      id: '/fr/compare'
      path: '/compare'
      fullPath: '/fr/compare'
      preLoaderRoute: typeof FrCompareRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/ai-tools': {
      id: '/fr/ai-tools'
      path: '/ai-tools'
      fullPath: '/fr/ai-tools'
      preLoaderRoute: typeof FrAiToolsRouteImport
      parentRoute: typeof FrRoute
    }
    '/ar/terms': {
      id: '/ar/terms'
      path: '/terms'
      fullPath: '/ar/terms'
      preLoaderRoute: typeof ArTermsRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/privacy-policy': {
      id: '/ar/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/ar/privacy-policy'
      preLoaderRoute: typeof ArPrivacyPolicyRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/news': {
      id: '/ar/news'
      path: '/news'
      fullPath: '/ar/news'
      preLoaderRoute: typeof ArNewsRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/learn': {
      id: '/ar/learn'
      path: '/learn'
      fullPath: '/ar/learn'
      preLoaderRoute: typeof ArLearnRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/features': {
      id: '/ar/features'
      path: '/features'
      fullPath: '/ar/features'
      preLoaderRoute: typeof ArFeaturesRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/download': {
      id: '/ar/download'
      path: '/download'
      fullPath: '/ar/download'
      preLoaderRoute: typeof ArDownloadRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/delete-account': {
      id: '/ar/delete-account'
      path: '/delete-account'
      fullPath: '/ar/delete-account'
      preLoaderRoute: typeof ArDeleteAccountRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/contact': {
      id: '/ar/contact'
      path: '/contact'
      fullPath: '/ar/contact'
      preLoaderRoute: typeof ArContactRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/compare': {
      id: '/ar/compare'
      path: '/compare'
      fullPath: '/ar/compare'
      preLoaderRoute: typeof ArCompareRouteImport
      parentRoute: typeof ArRoute
    }
    '/ar/ai-tools': {
      id: '/ar/ai-tools'
      path: '/ai-tools'
      fullPath: '/ar/ai-tools'
      preLoaderRoute: typeof ArAiToolsRouteImport
      parentRoute: typeof ArRoute
    }
    '/Teropdf/terms': {
      id: '/Teropdf/terms'
      path: '/terms'
      fullPath: '/Teropdf/terms'
      preLoaderRoute: typeof TeropdfTermsRouteImport
      parentRoute: typeof TeropdfRoute
    }
    '/Teropdf/privacy-policy': {
      id: '/Teropdf/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/Teropdf/privacy-policy'
      preLoaderRoute: typeof TeropdfPrivacyPolicyRouteImport
      parentRoute: typeof TeropdfRoute
    }
  }
}

interface TeropdfRouteChildren {
  TeropdfPrivacyPolicyRoute: typeof TeropdfPrivacyPolicyRoute
  TeropdfTermsRoute: typeof TeropdfTermsRoute
}

const TeropdfRouteChildren: TeropdfRouteChildren = {
  TeropdfPrivacyPolicyRoute: TeropdfPrivacyPolicyRoute,
  TeropdfTermsRoute: TeropdfTermsRoute,
}

const TeropdfRouteWithChildren =
  TeropdfRoute._addFileChildren(TeropdfRouteChildren)

interface ArRouteChildren {
  ArAiToolsRoute: typeof ArAiToolsRoute
  ArCompareRoute: typeof ArCompareRoute
  ArContactRoute: typeof ArContactRoute
  ArDeleteAccountRoute: typeof ArDeleteAccountRoute
  ArDownloadRoute: typeof ArDownloadRoute
  ArFeaturesRoute: typeof ArFeaturesRoute
  ArLearnRoute: typeof ArLearnRoute
  ArNewsRoute: typeof ArNewsRoute
  ArPrivacyPolicyRoute: typeof ArPrivacyPolicyRoute
  ArTermsRoute: typeof ArTermsRoute
  ArIndexRoute: typeof ArIndexRoute
}

const ArRouteChildren: ArRouteChildren = {
  ArAiToolsRoute: ArAiToolsRoute,
  ArCompareRoute: ArCompareRoute,
  ArContactRoute: ArContactRoute,
  ArDeleteAccountRoute: ArDeleteAccountRoute,
  ArDownloadRoute: ArDownloadRoute,
  ArFeaturesRoute: ArFeaturesRoute,
  ArLearnRoute: ArLearnRoute,
  ArNewsRoute: ArNewsRoute,
  ArPrivacyPolicyRoute: ArPrivacyPolicyRoute,
  ArTermsRoute: ArTermsRoute,
  ArIndexRoute: ArIndexRoute,
}

const ArRouteWithChildren = ArRoute._addFileChildren(ArRouteChildren)

interface FrRouteChildren {
  FrAiToolsRoute: typeof FrAiToolsRoute
  FrCompareRoute: typeof FrCompareRoute
  FrContactRoute: typeof FrContactRoute
  FrDeleteAccountRoute: typeof FrDeleteAccountRoute
  FrDownloadRoute: typeof FrDownloadRoute
  FrFeaturesRoute: typeof FrFeaturesRoute
  FrLearnRoute: typeof FrLearnRoute
  FrNewsRoute: typeof FrNewsRoute
  FrPrivacyPolicyRoute: typeof FrPrivacyPolicyRoute
  FrTermsRoute: typeof FrTermsRoute
  FrIndexRoute: typeof FrIndexRoute
}

const FrRouteChildren: FrRouteChildren = {
  FrAiToolsRoute: FrAiToolsRoute,
  FrCompareRoute: FrCompareRoute,
  FrContactRoute: FrContactRoute,
  FrDeleteAccountRoute: FrDeleteAccountRoute,
  FrDownloadRoute: FrDownloadRoute,
  FrFeaturesRoute: FrFeaturesRoute,
  FrLearnRoute: FrLearnRoute,
  FrNewsRoute: FrNewsRoute,
  FrPrivacyPolicyRoute: FrPrivacyPolicyRoute,
  FrTermsRoute: FrTermsRoute,
  FrIndexRoute: FrIndexRoute,
}

const FrRouteWithChildren = FrRoute._addFileChildren(FrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeropdfRoute: TeropdfRouteWithChildren,
  AiToolsRoute: AiToolsRoute,
  ArRoute: ArRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  FrRoute: FrRouteWithChildren,
  LearnRoute: LearnRoute,
  NewsRoute: NewsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
